import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavigationHeader, NavigationFooter } from "./components/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="fixed top-0 left-0 w-full bg-gray-800 text-white p-4 shadow-lg">
          <NavigationHeader />
        </header>
        <footer className="fixed bottom-0 left-0 w-full bg-gray-800 text-black p-4 shadow-lg">
          <NavigationFooter />
        </footer>
        {children}
      </body>
    </html>
  );
}
